import PopupProvider from "./context/popup/provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Petrona } from 'next/font/google';
import "./globals.css";
import Header from './components/shared/Header';
import Footer from './components/shared/Footer';

const petrona = Petrona({
  variable: "--font-petrona",
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '700'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${petrona.variable}`}>
        <Header />
        <PopupProvider>
          {children}
        </PopupProvider>
        <Footer />
      </body>
    </html>
  );
}